name: rust-gh-action
description: "Action to demonstrate how to develop GitHub Actions in Rust"

inputs:
  number:
    description: "Number to parse to a u32"
    required: true
    default: "0"
  cache:
    description: "Whether or not to cache docker layers (default: true)"
    required: true
    default: "true"

outputs:
  error:
    description: "The error if parsing failed"
    value: ${{ steps.run-container.outputs.error }}
  parsed:
    description: "Input parsed to u32 if parsing succeeds"
    value: ${{ steps.run-container.outputs.parsed_u32 }}

runs:
  using: "composite"
  steps:
    - name: Cache docker layers
      uses: jpribyl/action-docker-layer-caching@v0.1.1
      if: ${{ inputs.cache == 'true' }}
      continue-on-error: true
    - name: Build docker image
      run: |
        cd example-actions/composite
        docker build -t rust-gh-action .
      shell: bash
    - name: Run container
      id: run-container
      run: docker run -v $GITHUB_OUTPUT:/github_output rust-gh-action ${{ inputs.number }}
      shell: bash
