name: rust-gh-composite-action
description: "Example of a composite GitHub Action that builds and runs a docker container with Rust code"

inputs:
  number:
    description: "Number to parse to a u32"
    required: true
    default: "0"

outputs:
  error:
    description: "The error if parsing failed"
    value: ${{ steps.run-container.outputs.error }}
  parsed_u32:
    description: "Input parsed to u32 if parsing succeeded"
    value: ${{ steps.run-container.outputs.parsed_u32 }}

runs:
  using: "composite"
  steps:
    - name: Cache docker layers
      uses: jpribyl/action-docker-layer-caching@v0.1.1
      continue-on-error: true
    - name: Build docker image
      run: |
        cd example-actions/composite
        docker build -t rust-gh-composite-action .
      shell: bash
    - name: Run container
      id: run-container
      # $GITHUB_OUTPUT needs to be mounted in the container to /github_output for the outputs to be available to the runner
      run: docker run -v $GITHUB_OUTPUT:/github_output rust-gh-composite-action ${{ inputs.number }}
      shell: bash
