[package]
name = "rust-gh-action"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# gha_main = "0.0.1"
# gha_main = { path = "./../.." } # Use for local development
gha_main = { git = "https://github.com/avsaase/gha_main.git", branch = "multiline-string-outputs" }
