name: rust-gh-container-action
description: "Example of a container based GitHub Action that runs Rust code"

inputs:
  number:
    description: "Number to parse to a u32"
    required: true
    default: "0"

outputs:
  error:
    description: "The error if parsing failed"
  parsed_u32:
    description: "Input parsed to u32 if parsing succeeded"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.number }}
