[package]
name = "rust-gh-action"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# gha-main = "0.0.1"
# gha-main = { path = "./../.." } # Use for local development
gha-main = { git = "https://github.com/avsaase/gha_main.git" }
