name: Update example action lock files
on:
  push:
    paths:
      - src/**

jobs:
  update-lock-files:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      
      - name: Update lock files
        env: 
          CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
        run: |
          cargo update --manifest-path ./example-actions/container/Cargo.toml
          cargo update --manifest-path ./example-actions/composite/Cargo.toml
          cargo update --manifest-path ./example-actions/normal/Cargo.toml
      
      - name: Commit lock files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update example actions lock files
          file_pattern: 'Cargo.lock'

